version: "3.9"
services:
    redis:
        image: redis:latest
        container_name: redis-01
        ports:
            - "6379:6379"

    minio:
        image: minio/minio:latest
        container_name: minio-01
        ports:
            - "9000:9000"
            - "9001:9001"
        command: server /data --console-address ":9001"
        environment:
            MINIO_ROOT_USER: minio
            MINIO_ROOT_PASSWORD: minioadmin
        volumes:
            - /home/nene/docker/minio/data:/data
            - /home/nene/docker/minio/config:/root/.minio
