version: "3.9"

services:
    redis:
        container_name: redis
        image: 'redis:latest'
        ports:
            - '6379:6379'
        volumes:
            - /home/nene/docker/container/redis/redis.conf:/usr/local/etc/redis/redis.conf
        command: redis-server /usr/local/etc/redis/redis.conf
    minio:
        container_name: minio
        image: 'bitnami/minio:latest'
        ports:
            - '9000:9000'
            - '9001:9001'
        environment:
            - MINIO_ROOT_USER=minioadmin
            - MINIO_ROOT_PASSWORD=minioadmin