server:
    port: 8848
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/nene_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    servlet:
        multipart:
            max-file-size: 4MB
            max-request-size: 5MB
    redis:
        host: 127.0.0.1
        port: 6379
        password: nene
mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    global-config:
        db-config:
            logic-delete-field: delFlag
            logic-delete-value: 1
            logic-not-delete-value: 0
            id-type: auto
custom:
    request:
        excluded-urls:
            - /login
            - /user/register
            - /article/list
            - /link/all
            - /comment/list
            - /comment/subordinate/list
            - /swagger-ui/**
            - /swagger-resources/**
minio:
    access-key: minioadmin
    secret-key: minioadmin
    endpoint: http://127.0.0.1:9000